# Generated by Django 4.2.1 on 2023-06-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='crearted_at',
            new_name='Created_at',
        ),
    ]
